apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: queue
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
    tier: queue
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: queue
    spec:
      containers:
      - name: queue
        image: docker.io/spolfliet/newrelic-k8s-guestbook-rabbitmq:latest
        ports:
          - containerPort: 3000
        resources:
         requests:
             cpu: 50m
             memory: 100Mi
         limits:
             cpu: 200m
             memory: 300Mi
